SUBDIR=	alpm amdpm amdsmn amdtemp clockmod corecstat corepower coretemp
SUBDIR+=intpm kate km lm memtemp perfbias powernow
SUBDIR+=viapm wbsio

# Empty for concurrent build
#
SUBDIR_ORDERED=

.include <bsd.subdir.mk>
